### ISSUE TITLE
RSS/ATOM feed

### ISSUE THREAD

**Issue by vifino** [derrickturk/usethe.computer#1]
Hey!
While it certainly feels weird opening an issue on someone's blog,
I would really like it if you added an RSS feed which I can add to my readers.

I enjoy your content, but I don't have the time to check it regularly. Keep it up! :)

**Comment by derrickturk** [comment]
Thanks! That's a good idea - let me look into it.

**Comment by derrickturk** [comment]
Added in 8f8bacb thanks to @kbturk!

**Comment by vifino** [comment]
Very cool, hope that feed is generated and kept up to date though! :)
